name = "random-image-analyzer"
main = "src/index.ts"
compatibility_date = "2024-10-18"

[triggers]
crons = ["0 * * * *"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "PHOTO_DETAILS"
id = "ca2e0d0c09a44f8b84a9337789922b2a"
