name: Deploy

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        name: 'Build'
        steps:
            - name: 'Checkout repo'
              uses: actions/checkout@v4
            - name: 'Install dependencies'
              run: npm ci
            - name: 'Run tests'
              run: npm test
            - name: 'Deploy app'
              uses: cloudflare/wrangler-action@v3
              with:
                  wranglerVersion: "3.82.0"
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: deploy
            - name: 'Deploy scheduled handler'
              uses: cloudflare/wrangler-action@v3
              with:
                  wranglerVersion: "3.82.0"
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: deploy --config wrangler-scheduled.toml

